name: Linting with flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Perform flake8 linting
        run: |
          pip3 install flake8
          flake8 --version
          flake8 . --builtins=FileNotFoundError --count --select=E11,E22,E25,E26,E3,E71,F63,F7,F82,F84,W3,W503 --show-source --statistics
